"""csrf token on sessions

Revision ID: 5e1414fa1ab4
Revises: 77827210b345
Create Date: 2026-05-30 02:54:35.323699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5e1414fa1ab4'
down_revision: str | None = '77827210b345'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csrf_token', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('csrf_token')

    # ### end Alembic commands ###
